### ISSUE TITLE
after installing it my terminal loses the transparency.

### ISSUE THREAD

**Issue by ronyAhmed1200** [yashguptaz/calvera-dark.nvim#5]
I tried that. but after installing it with vim plug, my terminal lose it's transparency. These theme forced my terminal by making it a blue opaque background. whcih is not what i want..

**Comment by niyabits** [comment]
Hello, thanks for opening the issue
Add the line I have mentioned below -

If you're using vimscript (i.e. you have config in a .vim file) add
```vim
hi Normal guibg=NONE ctermbg=NONE
```

If you're using a lua config then add
```lua
vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
```

I would consider adding a transparent mode in the theme,
currently you might have a few opaque elements left.

**Comment by ronyAhmed1200** [comment]
Yeah it worked.. But now the comment line issue brings up.. It is hard to read the comments now.. 

![image](https://user-images.githubusercontent.com/75775786/125191535-c5ea3680-e264-11eb-94da-ef7c368e7c97.png)

and reading the line number are also difficult in here.. but the syntax of the code is nice.. 

![image](https://user-images.githubusercontent.com/75775786/125191700-9687f980-e265-11eb-8444-7fc411687039.png)


If look closely, then you will see there are comment lines too.. lol

**Comment by niyabits** [comment]
I have just opened #6  and it adds a transparent background mode and fixes your issues with
- Line Numbers
- Comments
- Cursorline

You can use,
```vim
Plug 'yashguptaz/calvera-dark.nvim', {'branch': 'dev'}
```
and
```vim
let g:calvera_transparentbg = 1
```

Let me know if you have any other feedback, I will be sure to make the changes accordingly.

**Comment by ronyAhmed1200** [comment]
Thanks for fixing it .. It solves my issue.. 

![image](https://user-images.githubusercontent.com/75775786/125200791-2a6dbb80-e28e-11eb-9848-099763120f58.png)

**Comment by niyabits** [comment]
@ronyAhmed1200 you might want to switch to the main branch now.
Also I have renamed `transparentbg` to `transparent_bg` as it follows the naming convention more closely.
```vim
let g:calvera_transparent_bg = 1
```
